name: Test

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          mkdir out
          go test -race ./... -coverprofile=out/coverage.txt -covermode=atomic

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: out/coverage.txt
